<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Victor Hong</Authors>
    <Description>Exposes a LLM agent on an XMPP server</Description>
    <RepositoryUrl>https://github.com/victorqhong/LlmAgents</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlmAgents\LlmAgents.csproj" />
    <ProjectReference Include="..\LlmAgents.Api\LlmAgents.Api.csproj" />
    <ProjectReference Include="..\LlmAgents.CommandLineParser\LlmAgents.CommandLineParser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="XmppDotNet" />
    <PackageReference Include="XmppDotNet.Extensions" />
    <PackageReference Include="XmppDotNet.Srv" />
    <PackageReference Include="XmppDotNet.Transport.Socket" />
  </ItemGroup>

</Project>
