<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Victor Hong</Authors>
    <Description></Description>
    <RepositoryUrl>https://github.com/victorqhong/LlmAgents</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlmAgents\LlmAgents.csproj" />
    <ProjectReference Include="..\LlmAgents.CommandLineParser\LlmAgents.CommandLineParser.csproj" />
  </ItemGroup>

</Project>
