# .github/workflows/pack.yml
name: Pack on merge to master

on:
  push:
    branches:
      - master          # triggers only when the branch that receives the push is `master`

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Install the same .NET SDK that is used by the CI
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3️⃣ Restore NuGet packages (so the pack step can resolve all references)
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build the solution (required for a successful pack)
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # 5️⃣ Pack the projects into NuGet packages
      - name: Pack
        run: dotnet pack --no-restore --configuration Release --output ./nupkgs

      # (Optional) Upload the .nupkg files as an artifact so you can download them later
      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: ./nupkgs/**/*.nupkg
